# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NFSNetworkingDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NFSNetworkingDemo

  pod 'NFSNetworking', :path => '../'

  target 'NFSNetworkingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
